builds:
  - id: macos
    goos:
      - darwin
    goarch:
      - amd64
    main: ./cmd/cvecli
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

    format_overrides:
      - goos: windows
        format: zip
release:
  disable: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
#signs:
#  - signature: "${artifact}.dmg"
#    ids:
#      - macos
#    cmd: gon
#    args: ["--log-level", "info", "--log-json", ".github/workflows/macos_amd64_config.json"]
#    artifacts: all
