before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: ./cmd/cvecli

  - id: windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    main: ./cmd/cvecli
    hooks:
      post:
        -
universal_binaries:
  - replace: true
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
