name: release

#on:
#  push:
#    tags:
#      - v*.*.*

on:
  push:

permissions:
  contents: write

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release -f .goreleaser.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Directories
        shell: bash
        run: |
          cd dist
          ls -la
          cd cvecli_darwin_arm64
          ls -la
      - name: Upload Linux 386 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_linux_386
          path: ./dist/cvecli_linux_386/cvecli
      - name: Upload Linux amd64 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_linux_amd64
          path: ./dist/cvecli_linux_amd64/cvecli
      - name: Upload Linux arm64 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_linux_arm64
          path: ./dist/cvecli_linux_arm64/cvecli
      - name: Upload macOS amd64 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_darwin_amd64
          path: ./dist/cvecli_darwin_amd64/cvecli
      - name: Upload macOS arm64 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_darwin_arm64
          path: ./dist/cvecli_darwin_arm64/cvecli
      - name: Upload Windows 386 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_windows_386
          path: ./dist/cvecli_windows_386/cvecli.exe
      - name: Upload Windows amd64 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_windows_amd64
          path: ./dist/cvecli_windows_amd64/cvecli.exe
      - name: Upload Windows arm64 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_windows_arm64
          path: ./dist/cvecli_windows_arm64/cvecli.exe

  sign_windows_binary:
    name: Sign and Timestamp Windows Binary
    needs: build_and_release
    runs-on: windows-latest
    steps:
      - name: Create dist directory
        shell: pwsh
        run: |
          mkdir dist
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.x.x'
      - name: Install AzureSignTool
        shell: pwsh
        run: |
          dotnet tool install --global AzureSignTool --version 3.0.0
      - name: Download Windows 386 binary
        uses: actions/download-artifact@v2
        with:
          name: cvecli_windows_386
          path: ./dist/cvecli_windows_386/cvecli.exe
      - name: Download Windows amd64 binary
        uses: actions/download-artifact@v2
        with:
          name: cvecli_windows_amd64
          path: ./dist/cvecli_windows_amd64/cvecli.exe
      - name: Download Windows arm64 binary
        uses: actions/download-artifact@v2
        with:
          name: cvecli_windows_arm64
          path: ./dist/cvecli_windows_arm64/cvecli.exe
      - name: Check Directories
        shell: pwsh
        run: |
          ls
          cd dist
          ls

