name: release

#on:
#  push:
#    tags:
#      - v*.*.*

on:
  push:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release -f .goreleaser.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Linux 386 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_linux_386
          path: ./dist/cvecli_linux_386/cvecli
      - name: Upload Linux amd64 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_linux_amd64
          path: ./dist/cvecli_linux_amd64/cvecli
      - name: Upload Linux arm64 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_linux_arm64
          path: ./dist/cvecli_linux_arm64/cvecli
      - name: Upload macOS amd64 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_darwin_amd64
          path: ./dist/cvecli_darwin_amd64/cvecli
      - name: Upload macOS arm64 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_darwin_arm64
          path: ./dist/cvecli_darwin_arm64/cvecli
      - name: Upload Windows 386 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_windows_386
          path: ./dist/cvecli_windows_386/cvecli.exe
      - name: Upload Windows amd64 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_windows_amd64
          path: ./dist/cvecli_windows_amd64/cvecli.exe
      - name: Upload Windows arm64 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_windows_arm64
          path: ./dist/cvecli_windows_arm64/cvecli.exe

  sign_windows_binaries:
    name: Sign and Timestamp Windows Binary
    needs: build
    runs-on: windows-latest
    steps:
      - name: Create dist directory
        shell: pwsh
        run: |
          mkdir dist
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.x.x'
      - name: Install AzureSignTool
        shell: pwsh
        run: |
          dotnet tool install --global AzureSignTool --version 3.0.0
      - name: Download Windows 386 binary
        uses: actions/download-artifact@v2
        with:
          name: cvecli_windows_386
          path: ./dist/cvecli_windows_386/cvecli.exe
      - name: Download Windows amd64 binary
        uses: actions/download-artifact@v2
        with:
          name: cvecli_windows_amd64
          path: ./dist/cvecli_windows_amd64/cvecli.exe
      - name: Download Windows arm64 binary
        uses: actions/download-artifact@v2
        with:
          name: cvecli_windows_arm64
          path: ./dist/cvecli_windows_arm64/cvecli.exe
      - name: Sign Windows binaries
        shell: pwsh
        run: |
          $386 = Get-ChildItem ./dist/cvecli_windows_386/cvecli.exe | % { $_.FullName }
          $amd64 = Get-ChildItem ./dist/cvecli_windows_amd64/cvecli.exe | % { $_.FullName }
          $arm64 = Get-ChildItem ./dist/cvecli_windows_arm64/cvecli.exe | % { $_.FullName }
          Add-Content -Path signing.txt -Value $386
          Add-Content -Path signing.txt -Value $amd64
          Add-Content -Path signing.txt -Value $arm64
          azuresigntool sign --description-url "https://github.com/wizedkyle/cvecli" --file-digest sha256 `
            --azure-key-vault-url ${{ secrets.AZURE_KEY_VAULT_URL }} `
            --azure-key-vault-client-id ${{ secrets.AZURE_KEY_VAULT_CLIENT_ID }} `
            --azure-key-vault-client-secret ${{ secrets.AZURE_KEY_VAULT_CLIENT_SECRET }} `
            --azure-key-vault-certificate ${{ secrets.AZURE_KEY_VAULT_CERTIFICATE }} `
            --azure-key-vault-tenant-id ${{ secrets.AZURE_KEY_VAULT_TENANT_ID }} `
            --timestamp-rfc3161 http://timestamp.sectigo.com `
            --timestamp-digest sha256 `
            --input-file-list signing.txt
      - name: Upload Signed Windows 386 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_windows_386_signed
          path: ./dist/cvecli_windows_386/cvecli.exe
      - name: Upload Signed Windows amd64 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_windows_amd64_signed
          path: ./dist/cvecli_windows_amd64/cvecli.exe
      - name: Upload Signed Windows arm64 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_windows_arm64_signed
          path: ./dist/cvecli_windows_arm64/cvecli.exe

  sign_and_notarise_macos_binaries:
    name: Sign and Notarise macOS binaries
    needs: build
    runs-on: macos-latest
    steps:
      - name: Create dist directory
        shell: bash
        run: |
          mkdir dist
      - name: Download macOS amd64 binary
        uses: actions/download-artifact@v2
        with:
          name: cvecli_darwin_amd64
          path: ./dist/cvecli_darwin_amd64/cvecli
      - name: Download macOS arm64 binary
        uses: actions/download-artifact@v2
        with:
          name: cvecli_darwin_arm64
          path: ./dist/cvecli_darwin_arm64/cvecli
      - name: Install Gon
        shell: bash
        run: |
          brew tap mitchellh/gon
          brew install mitchellh/gon/gon
      - name: Install signing certificates
        shell: bash
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          echo -n "$APPLE_DEV_CERT" | base64 --decode --output $CERTIFICATE_PATH
          security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
          security import $CERTIFICATE_PATH -P $APPLE_DEV_CERT_PASSWORD -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
        env:
          APPLE_DEV_CERT: ${{ secrets.APPLE_DEV_CERT }}
          APPLE_DEV_CERT_PASSWORD: ${{ secrets.APPLE_DEV_CERT_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      - name: Sign and notarise amd64 binary
        shell: bash
        run: |
          ls -la
          gon -log-level=indo -log-json .github/workflows/macos_amd64_config.json
        env:
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}


