name: release

#on:
#  push:
#    tags:
#      - v*.*.*

on:
  push:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release -f .goreleaser.yml --rm-dist
        env:
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Darwin amd64
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_darwin_amd64
          path: ./dist/cvecli_darwin_amd64/cvecli
      - name: Upload Darwin arm64
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_darwin_arm64
          path: ./dist/cvecli_darwin_arm64/cvecli
      - name: Upload linux amd64
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_linux_amd64
          path: ./dist/cvecli_linux_amd64/cvecli
      - name: Upload linux arm64
        uses: actions/upload-artifact@v2
        with:
          nama: cvecli_linux_arm64
          path: ./dist/cvecli_linux_arm64/cvecli
      - name: Upload Windows amd64
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_windows_amd64
          path: ./dist/cvecli_windows_amd64/cvecli.exe
      - name: Upload Windows arm64
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_windows_arm64
          path: ./dist/cvecli_windows_arm64/cvecli.exe

  sign_macos_binaries:
    name: Signing macOS binaries
    needs: build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download Binary
        uses: actions/download-artifact@v2
        with:
          name: cvecli_darwin_amd64
          path: ./dist/cvecli_darwin_amd64
      - name: Check Directory
        shell: bash
        run: |
          ls -la ./dist/cvecli_darwin_amd64
      - name: Install Gon
        shell: bash
        run: |
          brew tap mitchellh/gon
          brew install mitchellh/gon/gon
      - name: Configuring signing certificate
        shell: bash
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          echo -n "$APPLE_DEV_CERT" | base64 --decode --output $CERTIFICATE_PATH
          security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
          security import $CERTIFICATE_PATH -P $APPLE_DEV_CERT_PASSWORD -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
        env:
          APPLE_DEV_CERT: ${{ secrets.APPLE_DEV_CERT }}
          APPLE_DEV_CERT_PASSWORD: ${{ secrets.APPLE_DEV_CERT_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      - name: Sign macOS amd64 binary
        shell: bash
        run: |
          gon --log-level=info --log-json .github/workflows/macos_amd64_config.json
          gon --log-level=info --log-json .github/workflows/macos_arm64_config.json
        env:
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
      - name: Upload signed macOS amd64 dmg
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_darwin_amd64_signed_dmg
          path: ./cvecli_darwin_amd64.dmg
      - name: Upload signed macOS amd64 zip
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_darwin_amd64_signed_zip
          path: ./cvecli_darwin_amd64.zip
      - name: Upload signed macOS arm64 dmg
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_darwin_arm64-signed_dmg
          path: ./dist/cvecli_darwin_arm64.dmg
      - name: Upload signed macOS arm64 zip
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_darwin_arm64_signed_zip
          path: ./dist/cvecli_darwin_arm64.zip

  sign_windows_binaries:
    name: Sign and Timestamp Windows Binary
    needs: sign_macos_binaries
    runs-on: windows-latest
    steps:
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.x.x'
      - name: Install AzureSignTool
        shell: pwsh
        run: |
          dotnet tool install --global AzureSignTool --version 3.0.0
      - name: Download Windows amd64 binary
        uses: actions/download-artifact@v2
        with:
          name: cvecli_windows_amd64
          path: ./dist/cvecli_windows_amd64/cvecli.exe
      - name: Download Windows arm64 binary
        uses: actions/download-artifact@v2
        with:
          name: cvecli_windows_arm64
          path: ./dist/cvecli_windows_arm64/cvecli.exe
      - name: Sign Windows binaries
        shell: pwsh
        run: |
          $amd64 = Get-ChildItem ./dist/cvecli_windows_amd64/cvecli.exe | % { $_.FullName }
          $arm64 = Get-ChildItem ./dist/cvecli_windows_arm64/cvecli.exe | % { $_.FullName }
          Add-Content -Path signing.txt -Value $386
          Add-Content -Path signing.txt -Value $amd64
          Add-Content -Path signing.txt -Value $arm64
          azuresigntool sign --description-url "https://github.com/wizedkyle/cvecli" --file-digest sha256 `
            --azure-key-vault-url ${{ secrets.AZURE_KEY_VAULT_URL }} `
            --azure-key-vault-client-id ${{ secrets.AZURE_KEY_VAULT_CLIENT_ID }} `
            --azure-key-vault-client-secret ${{ secrets.AZURE_KEY_VAULT_CLIENT_SECRET }} `
            --azure-key-vault-certificate ${{ secrets.AZURE_KEY_VAULT_CERTIFICATE }} `
            --azure-key-vault-tenant-id ${{ secrets.AZURE_KEY_VAULT_TENANT_ID }} `
            --timestamp-rfc3161 http://timestamp.sectigo.com `
            --timestamp-digest sha256 `
            --input-file-list signing.txt
      - name: Upload Signed Windows amd64 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_windows_amd64_signed
          path: ./dist/cvecli_windows_amd64/cvecli.exe
      - name: Upload Signed Windows arm64 binary
        uses: actions/upload-artifact@v2
        with:
          name: cvecli_windows_arm64_signed
          path: ./dist/cvecli_windows_arm64/cvecli.exe

