name: Cvecli Tests

on: [pull_request, push]

env:
  GOVERSION: '1.18'

jobs:
  run_tests:
    name: Run Cvecli Linux Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Setup Go Environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build Cvecli
        run: go build ./cmd/cvecli
      - name: Run Tests
        run: go test ./...
